/* tslint:disable */
/* eslint-disable */
/**
 * 后台接口
 * 这是用于管理的博客后台接口 Powered by .NET 6.0.7 on WINDOWS
 *
 * OpenAPI spec version: The Current Version: Full-v1
 * Contact: me@zhaifanhua.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CUserAuthorityDto
 */
export interface CUserAuthorityDto {
    /**
     * 
     * @type {string}
     * @memberof CUserAuthorityDto
     */
    parentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CUserAuthorityDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CUserAuthorityDto
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CUserAuthorityDto
     */
    description?: string | null;
}
