/* tslint:disable */
/* eslint-disable */
/**
 * 后台接口
 * 这是用于管理的博客后台接口 Powered by .NET 6.0.7 on WINDOWS
 *
 * OpenAPI spec version: The Current Version: Full-v1
 * Contact: me@zhaifanhua.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CUserAccountDto
 */
export interface CUserAccountDto {
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    avatarPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    nickName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    signature?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CUserAccountDto
     */
    gender?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    address?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CUserAccountDto
     */
    birthday?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CUserAccountDto
     */
    registerIp?: string | null;
}
