# 名称
name: ZhaifanhuaBlog.UI

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches: [ main ]
# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # 拉取代码
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: echo $path
    - run: yarn
    - run: yarn dev
