# 名称
name: ZhaifanhuaBlog.UI

# 触发条件：在 push 和 pull 到 main 分支后
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .\ZhaifanhuaBlog.UI\

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    # 拉取代码
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
    # 环境
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn  --check-files
    - name: Build
      run: yarn dev
    - name: Test
      run: yarn test
